-- V10: Database Schema Fixes and Optimizations
-- Note: V9 already contains ON DELETE CASCADE for invitation_tokens
-- Note: V5 and V6 correctly sequenced depots table creation and foreign key assignment

-- 1. Multi-Tenant Grounding on vehicles and depots
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS company_id BIGINT;
ALTER TABLE depots ADD COLUMN IF NOT EXISTS company_id BIGINT;

-- 2. Clean Status Mapping on users
-- Drop is_active column since status column natively handles state (added in V9)
ALTER TABLE users DROP COLUMN IF EXISTS is_active;
ALTER TABLE users ALTER COLUMN status SET DEFAULT 'PENDING_ACTIVATION';

-- Update existing records that might have 'active' (lowercase) to 'ACTIVE' (uppercase)
UPDATE users SET status = 'ACTIVE' WHERE status = 'active';

-- 3. Mobile GPS Event Binding
-- Add driver_id to track mobile telemetry directly to the user record
ALTER TABLE gps_events ADD COLUMN IF NOT EXISTS driver_id BIGINT REFERENCES users(id);

-- 4. Driver Shifts Foreign Keys
-- Ensure driver_shifts exists before adding constraints in case Hibernate hasn't created it yet
CREATE TABLE IF NOT EXISTS driver_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT,
    vehicle_id BIGINT,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status VARCHAR(255)
);

-- Note: We can't use DROP CONSTRAINT IF EXISTS safely in H2 without ignoring errors, 
-- but since we are creating IF NOT EXISTS, we can just let Hibernate manage the foreign keys 
-- for this specific table, or assume they are added by Hibernate.
-- We will just ensure the table structure is there for Flyway consistency.
